#!/usr/bin/env bash
#a Bash script that will display information about subdomains.
subdomain_info () {
	local domain="$1"
	local subdomain="$2"
	if [ -z "$subdomain" ]; then
		mysubdomains=("www" "lb-01" "web-01" "web-02")
	else
		mysubdomains=("$subdomain")
	fi
	for sub in "${mysubdomains[@]}"; do
		result=$(dig "$sub.$domain" +short)
		if [ -z "$result" ]; then 
			echo "The subdomain $sub is not configured or does not exist."
		else
			echo "The subdomain $sub is a A record and points to $result"
		fi
	done
}

if [ $# -lt 1 ]; then
	echo "Usage: $0 <domain> [<subdomai>]"
	exit 1
fi

domain="$1"
subdomain="$2"

subdomain_info "$domain" "$subdomain"
