#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
if [ $# -ne 4 ]; then
    echo  "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
dest_ip=$2
dest_username=$3
ssh_path=$4

scp -i "$ssh_path" -o StrictHostKeyChecking=no "$file_path" "$dest_username@$dest_ip:~/"
