#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy=2.0.\*

if ! grep -q "ENABLED=" /etc/default/haproxy; then
    sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
else
    sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy # make ENABLED=1
fi

# Configure HAProxy by appending a frontend and backend configuration to /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\
frontend load_balancer\n\
\tbind *:80\n\
\tmode http\n\
\tdefault_backend web_servers\n\
\n\
backend web_servers\n\
\tbalance roundrobin\n\
\tserver 271576-web-01 34.229.68.30:80 check\n\
\tserver 271576-web-02 18.235.234.83:80 check" /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart
