#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0
minutes=1
while [ $hours -lt 12 ]
do
    while [ $minutes -lt 60 ]
    do
        echo $minutes
	(( minutes++ ))
    done
    minutes=1
    echo "Hour: $hours"
    (( hours++ ))
done
