#!/usr/bin/env bash
# a Bash script that creates an RSA key pair.
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# passphrase betty

ssh-keygen -t rsa -b 4096 -f school -N betty
